export const CAREERS = [
  {
    position: 'Senior Frontend Engineer',
    company: 'Re Partners',
    logo: '/images/careers/Re.jpg',
    location: 'United States',
    location_type: 'Remote',
    type: 'Fulltime',
    start_date: 'Sep 2018',
    end_date: 'Mar 2022',
    link: 'https://www.re-partners.com/',
  },
  {
    position: 'Full Stack Engineer',
    company: 'Adobe',
    logo: '/images/careers/Adobe.jpg',
    location: 'United States',
    location_type: 'Remote',
    type: 'Fulltime',
    start_date: 'Mar 2015',
    end_date: 'Aug 2018',
    link: 'https://www.adobe.com/',
  },
  {
    position: 'Frontend Developer',
    company: 'Zuora',
    logo: '/images/careers/Zuora.jpg',
    location: 'United States',
    location_type: 'On-site',
    type: 'Fulltime',
    start_date: 'Apr 2014',
    end_date: 'Feb 2015',
    link: 'https://www.zuora.com/',
  },
  {
    position: "Bachelor's Degree",
    company: 'University of California, Berkeley',
    logo: '/images/careers/Univ.jpg',
    location: '',
    location_type: '',
    type: '',
    start_date: 'Apr 2010',
    end_date: 'Mar 2014',
    link: 'https://linktr.ee/ucberkeley',
  },
];
